<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">

    <parent>
        <groupId>org.egovframe.rte</groupId>
        <artifactId>egovframe-rte-root</artifactId>
        <version>5.0.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>egovframe-rte-fdl-string</artifactId>
    <packaging>jar</packaging>
    <name>org.egovframe.rte.fdl.string</name>
    <description>The eGovernment Standard Framework</description>
    <url>https://www.egovframe.go.kr</url>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <properties>
        <org.egovframe.rte.version>5.0.0</org.egovframe.rte.version>
        <jakarta.annotation.version>3.0.0</jakarta.annotation.version>
        <commons.codec.version>1.18.0</commons.codec.version>
        <easymock.version>5.3.0</easymock.version>
    </properties>

    <dependencies>
        <!-- eGovFramework -->
        <dependency>
            <groupId>org.egovframe.rte</groupId>
            <artifactId>egovframe-rte-fdl-logging</artifactId>
            <version>${org.egovframe.rte.version}</version>
        </dependency>

        <!-- Spring -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${spring.framework.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <version>${spring.framework.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- Jakarta APIs -->
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>${jakarta.annotation.version}</version>
        </dependency>

        <!-- Commons & Utils -->
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>${commons.codec.version}</version>
        </dependency>
        <dependency>
            <groupId>org.easymock</groupId>
            <artifactId>easymock</artifactId>
            <version>${easymock.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- JUnit -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
