language: java
jdk:
  - openjdk8

branches:
  only:
    - ci-setting

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - your@Email.com

addons:
  sonarcloud:
    organization: "openlenalab"
    token:
      secure: "PqjTJBzH0Xi06PZd3IUR8rl00FuDKcGMaWCjJPemWUt/8WcLjdmN2Fx6/Zgq/hHQXI8q+J/c00WtMJOIpbQZUQBy5krvK/hHoduJocJGS0PMB8SAz0TQ0dyusS0vVK1qpNzb6WlQlTOQ8tL5jsD++4Mhvwbi+OfacTdIDo6zLakHfUYdNTyR7ruCrX+AlKTGvtPO64mAK8vFZrT3DTImQ6Uon9Vh4gpw3f6tfbeMAtMSIRCJzI2634pEPaFHh0j0cKsWEGJLuohBPbPr3D9SGI8qlTq+0PcYppLPdQ7KIDGde9GatXjBvMD0MvoFB6fTDkU96Y3FO1f+/F0A0WFZG/I6+zX09pn6OZ15lvfjA2y9atRReUCzmUHCM+SP4mKqiUj45zs80wuGcfzTzwIX8e9AvNLJ/hKbx9tizEDF/478lm3hpUpmrFsJRttlVZAm62LcEzFTVvIrGPPywwb7Yn/SeX0zUy+LF+Y0ZJESg5tlrK7wgLAkzofaIBiadMcDXDFWHHomRoJ97uDEVP+88mD5dNYgvp5iEZ5BbFAVJaOhiwNyOXva2ccasJiUITYpoZOOyd9S6vvO7/9mah6d0OrQVZhrXuOfVaK6txAoZTfv0WsXaO+EHpqbHOHVfIvTGTZHSSXAxd7l/aRF5Fr1Xo4uftZltzExP5PuQD84XTw="

script:
  - mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 11 --target $JAVA_HOME
  - find ./ -name "%jacoco%"
  - mvn -B sonar:sonar -Dsonar.projectKey=openlenalab_egovframe-runtime  -Dsonar.coverage.jacoco.xmlReportPaths=$(find "$(pwd)" -path '*jacoco.xml' | sed 's/.*/&/' | tr '\n' ',')
