-- ====================================
-- DROP TABLES (if they exist)
-- ====================================
DROP TABLE sample IF EXISTS;
COMMIT;

-- ====================================
-- CREATE TABLE: sample
-- ====================================
CREATE TABLE sample
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id   VARCHAR(16) NOT NULL,
    name        VARCHAR(50),
    description VARCHAR(100),
    use_yn      CHAR(1),
    reg_user    VARCHAR(10)
);
COMMIT;
