<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">

    <parent>
        <groupId>org.egovframe.rte</groupId>
        <artifactId>egovframe-rte-root</artifactId>
        <version>5.0.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>egovframe-rte-fdl-filehandling</artifactId>
    <packaging>jar</packaging>
    <name>org.egovframe.rte.fdl.filehandling</name>
    <description>The eGovernment Standard Framework</description>
    <url>https://www.egovframe.go.kr</url>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <properties>
        <org.egovframe.rte.version>5.0.0</org.egovframe.rte.version>
        <jakarta.annotation.version>3.0.0</jakarta.annotation.version>
        <commons.io.version>2.18.0</commons.io.version>
        <commons.lang3.version>3.18.0</commons.lang3.version>
        <commons.vfs2.version>2.10.0</commons.vfs2.version>
    </properties>

    <dependencies>
        <!-- eGovFramework -->
        <dependency>
            <groupId>org.egovframe.rte</groupId>
            <artifactId>egovframe-rte-fdl-string</artifactId>
            <version>${org.egovframe.rte.version}</version>
        </dependency>

        <!-- Spring -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <version>${spring.framework.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- Jakarta APIs -->
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>${jakarta.annotation.version}</version>
        </dependency>

        <!-- Commons & Utils -->
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${commons.io.version}</version>
        </dependency>
        <!--CVE-2025-48924: 취약점 보완용 업데이트 -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons.lang3.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-vfs2</artifactId>
            <version>${commons.vfs2.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>commons-logging</artifactId>
                    <groupId>commons-logging</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>maven-scm-api</artifactId>
                    <groupId>org.apache.maven.scm</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>maven-scm-provider-svnexe</artifactId>
                    <groupId>org.apache.maven.scm</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- JUnit -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
